[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://your-backend-domain.com"
  REACT_APP_BACKEND_URL = "https://your-backend-domain.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://your-backend-domain.com"
  REACT_APP_BACKEND_URL = "https://your-backend-domain.com"
